travis:
  secure:
    BINSTAR_TOKEN: Fv5KV6F3K2K66nrrcrqPFOT0IkfoHwe3xRB2bppjyITqqbtq02oDHy1snEdZKVXMkiFqjCbFEHOV28S8ENjtbi7qiVksLyiL25my/039o8rYlPI+HEAWaWY82nFFgMz0ygfPgAwLfl1xwharst9hWppAVjyvWRtrxioddXygBdRpvxaJS6x0TsaJ0jec+uM6FaVO1KR8qgyx5HkiQcHl2QJkElrDL8Qny98xczCeLMRuFZPkno9xu7F1ue10YZM+nOwvDrhnro80EK7mqMsuaQN5KABgrNIMpbrkm5E6ioOYS7xHBaoJdwuvRokVxcYM6AVwkLuiekswClZ8DkbhWRh5BWrT5Oy4uGx0Y40RW9ljQHI89CRbIZVMRvGk1vKSGgVmgyaS9Uljcxe7k2upeYpko0/0YdeDZiWina0AnSNhMhpil4JkuCdM8+6HbSq/l7KfZK4yPPks0R5qay/ND6rb7KKT551Rcphk6ZhXMrPHUibt0nuFqdVCESEfF5ngTqGeUGGxRTw9NKM8CFkARzVFdayeRQE0wHsrTwwEP6p5KOTLBDsNUqg2z27pTpuNVz4U4Gn44uFkGpa4QpDCxvqs3msVsG8UscFHNMZvw8qA1UgLdfbick+hQNeGUHhN/kl96yiZRRc9b7E8HvzUUqWzDQkiBkOn/x95sFXRJ9Q=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
